version: "3.7"

services:
  app:
    build:
      args:
        user: roger
        uid: 1000
      context: ./docker-compose/php
      dockerfile: Dockerfile
    container_name: php-api-rest
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - lumen

  db:
    image: mysql:5.7
    container_name: db-api-rest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - lumen

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx-api-rest
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lumen

networks:
  lumen:
    driver: bridge